In [2]:
import pandas as pd 
import numpy as np 
import time


In [2]:
## FIND APPROPRIATE DELIMITER FOR THIS FILE ##

# Load in the .txt file using pandas library
file_path = 'Asgmnt1_data.txt'

# Try reading the file with different delimiters: 
for delimiter in [',', '\t', ' ', ';']:
    try:
        df = pd.read_csv(file_path, delimiter=delimiter)
        print(f"Delimiter '{delimiter}' works. Here's the first few rows:")
        print(df.head())
    except Exception as e:
        print(f"Delimiter '{delimiter}' failed. Error: {e}")


Delimiter ',' works. Here's the first few rows:
  4.9453511e+01   3.7213064e+01   3.8600731e+01   4.7251342e+01   2.1792191e+01   1.2224262e+01  -3.7136485e+00  -3.4253242e+01  -2.6037303e+01  -1.5913134e+01  -5.1096483e+01  -2.5872638e+01  -3.5067489e+01  -4.5702715e+01  -4.7742929e+01  -5.9234083e+01  -6.5946738e+01  -7.1318081e+01  -5.8019709e+01  -8.3698790e+01  -1.3979711e+02  -1.0157172e+02  -9.2582577e+01  -8.1728295e+01  -7.7493890e+01  -1.2785409e+02  -9.7469249e+01  -1.1131852e+02  -1.2335508e+02  -1.2151637e+02  -1.2510259e+02  -1.2396317e+02  -1.2394281e+02  -1.4373965e+02  -1.5250890e+02  -1.1327672e+02  -1.3765092e+02  -1.0530779e+02  -1.5210310e+02  -1.4520114e+02  -1.0427060e+02  -1.0360206e+02  -1.5107493e+02  -1.2479100e+02  -1.0021476e+02  -9.8192358e+01  -1.4805352e+02  -8.7202275e+01  -1.0326303e+02  -1.0859445e+02  -1.1402580e+02  -1.2494321e+02  -9.9577597e+01  -1.0222275e+02  -4.6261721e+01  -8.3816650e+01  -8.6028340e+01  -7.7584358e+01  -8.4115838e+01  -2.4809

In [3]:
# Open .txt file using appropriate delimiter
df_data = pd.read_csv('Asgmnt1_data.txt', delimiter=',', header=None)

# Clean up the extra spaces and then split the columns
df_data_clean = df_data[0].str.strip().replace(r'\s+', ' ', regex=True)

# SPlit the columns using a single space as the delimiter
df_data_split = df_data_clean.str.split(' ', expand=True)

# Convert to numeric, coercing any non-convertible values to NaN
df_data_numeric = df_data_split.apply(pd.to_numeric, errors='coerce')


# Ensure datatypes are numeric
print(df_data_numeric.shape)
print(df_data_numeric.head())

(16000, 128)
          0           1           2           3           4           5    \
0   49.453511   37.213064   38.600731   47.251342   21.792191   12.224262   
1  116.351130  119.300940  115.335630  102.958480   93.892301  112.556110   
2  -64.330794  -41.407368  -11.183825   27.777015  -20.535299   21.397063   
3  -27.522102  -33.564326 -100.076630  -61.023008  -53.938068  -73.929577   
4  157.764140  155.667740  183.326010  173.800080  176.371980  136.548550   

          6           7           8           9    ...         118  \
0   -3.713649  -34.253242  -26.037303  -15.913134  ...  105.555050   
1  100.270700  104.207060  130.333430  141.496550  ...   53.871534   
2  -16.168908   12.465869   11.441911   29.623230  ...  -97.474761   
3  -70.363867  -53.234154  -77.713490 -131.928860  ...   50.261319   
4  163.214940  139.592290  128.174920  155.566850  ...  165.444990   

          119         120         121         122         123         124  \
0  112.771820   64.018661 

In [4]:
# Z-normalize across ROWS
df_norm_data = df_data_numeric.apply(lambda x: (x - x.mean()) / (x.std()), axis=1) # axis = 1 indicates row
print(df_norm_data.shape)
print(df_norm_data.head())

(16000, 128)
        0         1         2         3         4         5         6    \
0  0.491177  0.363640  0.378098  0.468232  0.202965  0.103274 -0.062788   
1  1.396328  1.431788  1.384120  1.235331  1.126344  1.350707  1.203020   
2 -0.580587 -0.367559 -0.086690  0.275375 -0.173594  0.216086 -0.133016   
3 -0.244557 -0.293081 -0.827236 -0.513600 -0.456701 -0.617252 -0.588616   
4  1.120802  1.105776  1.304018  1.235740  1.254174  0.968738  1.159871   

        7         8         9    ...       118       119       120       121  \
0 -0.380989 -0.295385 -0.189898  ...  1.075715  1.150909  0.642935  0.745957   
1  1.250340  1.564413  1.698608  ...  0.645242  0.755643  0.887408  1.058602   
2  0.133088  0.123572  0.292532  ... -0.888595 -1.102518 -0.986267 -0.967187   
3 -0.451048 -0.647640 -1.083039  ...  0.380116  0.486544  0.214305  0.217024   
4  0.990554  0.908719  1.105052  ...  1.175855  1.373940  1.421743  1.401498   

        122       123       124       125       126    

In [5]:
## DISTANCE MATRIX USING EUCLIDEAN DISTANCE ##
# euclidean distance function #
def euclidean_distance(row1, row2):
    return np.sqrt(np.sum((row1 - row2) ** 2))

**Calculate Euclidean Distance on full, normalized dataset**

In [60]:
## Calculate the Euclidean Distance on half of the normalized dataset ##

# collect time to calculate euclidean distance
start_time = time.time()

# Save the rows into an empty distance matrix
num_rows = df_norm_data.shape[0]
euclidean_distance_matrix = pd.DataFrame(np.zeros((num_rows, num_rows)))

# Euclidean Distance: Finding differences between samples in a pairwise fashion
for i in range(num_rows):
    for j in range(i, num_rows): # only computes for upper triangle (j >= i)
        dist = euclidean_distance(df_norm_data.iloc[i], df_norm_data.iloc[j])
        euclidean_distance_matrix.iat[i, j] = dist 
        euclidean_distance_matrix.iat[i, j] = dist # This is an error: resulted in no copying over of upper triangle. Should have been euclidean_distance_matrix.iat[j, i] = dist

end_time_df = time.time()

# Calculate elapsed time
elapsed_time_df = end_time_df - start_time

print(f'Time it takes to calculate euclidean distance on total dataframe: {elapsed_time_df/60} minutes')

print("First few values: ", euclidean_distance_matrix.head())
print("Last few values: ", euclidean_distance_matrix.tail())

Time it takes to calculate euclidean distance on total dataframe: 461.9756764213244 minutes
First few values:     0          1          2          3          4          5          6      \
0    0.0  17.922421  22.311169   5.894622   9.522165  22.025037   5.323783   
1    0.0   0.000000  13.740949  20.484951  11.178109  15.029705  17.718695   
2    0.0   0.000000   0.000000  21.727726  20.459687   4.680156  21.994713   
3    0.0   0.000000   0.000000   0.000000  13.876061  21.194551   7.321039   
4    0.0   0.000000   0.000000   0.000000   0.000000  20.892953   9.763212   

       7          8          9      ...      15990      15991      15992  \
0  17.094768   3.522726  17.665329  ...  16.172083  16.026503  16.181014   
1   8.053235  17.170589   4.236545  ...  15.595609  16.172143  16.127174   
2  14.867467  22.212790  13.976920  ...  15.596208  16.010622  16.057165   
3  19.387628   7.185308  20.402490  ...  16.186764  15.664651  15.907454   
4  11.510070   8.597964  10.898268  ... 

In [18]:
## Try block_size method when calculating the euclidean distance matrix ##
start_time = time.time()

# Save the rows into an empty distance matrix
num_rows = df_norm_data.shape[0]
block_size = 10000
euclidean_distance_matrix_2 = np.zeros((num_rows, num_rows), dtype=np.float32)

# Euclidean Distance: Finding differences between samples in a pairwise fashion
for i in range(0, num_rows, block_size):
    for j in range(i, num_rows, block_size): # only computes for upper triangle (j >= i)
        block_i = df_norm_data.iloc[i:i+block_size].to_numpy()
        block_j = df_norm_data.iloc[j:j+block_size].to_numpy()
        
        # pairwise distances between blocks
        for row_i in range(block_i.shape[0]):
            for row_j in range(block_j.shape[0]):
                dist = euclidean_distance(block_i[row_i], block_j[row_j])
                euclidean_distance_matrix_2[i+row_i, j+row_j] = dist 
                euclidean_distance_matrix_2[j+row_j, i+row_i] = dist

end_time_df = time.time()

# Calculate elapsed time
elapsed_time_df = end_time_df - start_time

euclidean_distance_matrix_2 = pd.DataFrame(euclidean_distance_matrix_2)

print(f'Time it takes to calculate euclidean distance on total dataframe: {elapsed_time_df/60} minutes')

print("First few values: ", euclidean_distance_matrix_2.head())
print("Last few values: ", euclidean_distance_matrix_2.tail())

Time it takes to calculate euclidean distance on total dataframe: 27.030476347605386 minutes
First few values:         0          1          2          3          4          5      \
0   0.000000  17.922421  22.311169   5.894622   9.522165  22.025038   
1  17.922421   0.000000  13.740949  20.484951  11.178109  15.029705   
2  22.311169  13.740949   0.000000  21.727726  20.459686   4.680156   
3   5.894622  20.484951  21.727726   0.000000  13.876060  21.194551   
4   9.522165  11.178109  20.459686  13.876060   0.000000  20.892952   

       6          7          8          9      ...      15990      15991  \
0   5.323783  17.094769   3.522726  17.665329  ...  16.172083  16.026503   
1  17.718695   8.053234  17.170589   4.236545  ...  15.595609  16.172144   
2  21.994713  14.867467  22.212790  13.976920  ...  15.596208  16.010622   
3   7.321040  19.387629   7.185308  20.402491  ...  16.186764  15.664651   
4   9.763212  11.510070   8.597964  10.898268  ...  16.318897  16.073332   

    

__Wavelet Transform and Euclidean Distance__

In [14]:
## TRANSFORM DATA USING WAVELET TRANSFORM ##
# USE THE FIRST FOUR COEFFICIENTS TO CALCULATE THE DISTANCE MATRIX

## Generate the 128 x 128 Haar wavelet matrix directly
haar_matrix = np.zeros((128, 128))

# First row of Haar matrix
haar_matrix[0, :] = 1 / np.sqrt(128)

# remaining rows in Haar matrix
n = 128
row = 1
length = n // 2

while length >= 1 and row < 128:
    for i in range(length):
        haar_matrix[row, 2 * i] = 1 
        haar_matrix[row, 2 * i + 1] = 1 
        if row + 1 < 128:
            haar_matrix[row + 1, 2 * i ] = 1 
            haar_matrix[row + 1, 2 * i + 1] = -1 
        row += 2
    length //= 2

# Normalize each row to become unit vector
for i in range(haar_matrix.shape[0]):
    row_norms = np.linalg.norm(haar_matrix[i])
    haar_matrix[i] = haar_matrix[i] / row_norms

H_128 = pd.DataFrame(haar_matrix).astype(np.float32)
print(H_128.head())



        0         1         2         3         4         5         6    \
0  0.088388  0.088388  0.088388  0.088388  0.088388  0.088388  0.088388   
1  0.707107  0.707107  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.707107 -0.707107  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.707107  0.707107  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.707107 -0.707107  0.000000  0.000000  0.000000   

        7         8         9    ...       118       119       120       121  \
0  0.088388  0.088388  0.088388  ...  0.088388  0.088388  0.088388  0.088388   
1  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

        122       123       124       125       126       127  
0  0

In [21]:
## Verify rows are unit vectors and orthogonal ##
# Unit Vector #
row_unit_vector = np.linalg.norm(haar_matrix, axis=1)  # rows in matrix
print("unit vectors ", row_unit_vector)
print("Number of unit vectors (rows): ", len(row_unit_vector))

## Orthogonality ##
orth_vectors_wavelet = np.dot(haar_matrix[2], haar_matrix[3]) # checking orthogonality between first and second vector
print("Resulting dot product between second and third rows: ", orth_vectors_wavelet) # orth_vectors should be zero

unit vectors  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
Number of unit vectors (rows):  128
Resulting dot product between second and third rows:  0.0


In [16]:
# Create array to store the first four coefficients
wavelet_four_coeffs = np.zeros((df_norm_data.shape[0], 4)) 

for i in range(df_norm_data.shape[0]): # iterate through each row
    row = df_norm_data.iloc[i, :].values

    # Transformation: matrix multiplication
    transformed_row = np.dot(row, haar_matrix.T)

    # Store first four coefficients from transformed row
    wavelet_four_coeffs[i, :] = transformed_row[:4]

df_wavelet_coeffs = pd.DataFrame(wavelet_four_coeffs, columns=[f'Coeff_{i+1}' for i in range(4)]).astype(np.float32)
print("Shape of the wavelet tranformed dataset: ", df_wavelet_coeffs.shape)
print(df_wavelet_coeffs.head())



Shape of the wavelet tranformed dataset:  (16000, 4)
        Coeff_1   Coeff_2   Coeff_3   Coeff_4
0 -9.506285e-16  0.604446  0.090182  0.598446
1 -6.106227e-16  1.999780 -0.025074  1.852232
2 -1.401657e-15 -0.670440 -0.150634  0.133420
3  9.586516e-16 -0.380168  0.034312 -0.948114
4  5.551115e-16  1.574428  0.010625  1.795880


In [17]:
## Euclidean Distance for wt using level = 4 ##

start_time_WT = time.time()

# Save the rows into an empty distance matrix
num_rows = df_wavelet_coeffs.shape[0]
block_size = 1000
euclidean_distance_matrix_wt = np.zeros((num_rows, num_rows), dtype=np.float32)

# Euclidean Distance: Finding differences between samples in a pairwise fashion
for i in range(0, num_rows, block_size):
    for j in range(i, num_rows, block_size): # only computes for upper triangle (j >= i)
        block_i = df_wavelet_coeffs.iloc[i:i+block_size].to_numpy()
        block_j = df_wavelet_coeffs.iloc[j:j+block_size].to_numpy()
        
        # pairwise distances between blocks
        for row_i in range(block_i.shape[0]):
            for row_j in range(block_j.shape[0]):
                dist = euclidean_distance(block_i[row_i], block_j[row_j])
                euclidean_distance_matrix_wt[i+row_i, j+row_j] = dist 
                euclidean_distance_matrix_wt[j+row_j, i+row_i] = dist

end_time_WT = time.time()

# Calculate elapsed time
elapsed_time_WT = end_time_WT - start_time_WT

euclidean_distance_matrix_wt = pd.DataFrame(euclidean_distance_matrix_wt)

print(f'Time it takes to calculate euclidean distance on wt dataframe: {elapsed_time_WT/60} minutes')
print("First few values: ", euclidean_distance_matrix_wt.head())
print("Last few values: ", euclidean_distance_matrix_wt.tail())

Time it takes to calculate euclidean distance on wt dataframe: 19.04857404232025 minutes
First few values:        0         1         2         3         4         5         6      \
0  0.000000  1.879420  1.378251  1.834240  1.543063  2.213871  1.485438   
1  1.879420  0.000000  3.178074  3.675543  0.430551  4.010577  3.217623   
2  1.378251  3.178074  0.000000  1.134980  2.798072  0.966162  1.245424   
3  1.834240  3.675543  1.134980  0.000000  3.369052  1.055619  0.629483   
4  1.543063  0.430551  2.798072  3.369052  0.000000  3.656582  2.949074   

      7         8         9      ...     15990     15991     15992     15993  \
0  2.074490  0.559462  1.560473  ...  0.754352  2.933563  3.340696  0.768846   
1  1.635748  1.784725  0.722546  ...  2.208749  4.811296  5.217406  1.380839   
2  2.919617  1.701152  2.738880  ...  1.051522  1.752983  2.226897  2.130362   
3  3.476953  1.940957  3.390970  ...  1.947211  1.295013  1.601296  2.376883   
4  1.579431  1.542054  0.361255  ...  1.8

**PCA, select best four PC, calculate Euclidean Distance**

In [12]:
## Normalize original dataset per column ##
df_norm_col_data = df_norm_data.apply(lambda x: (x - x.mean()) / (x.std())).astype(np.float32) # df_data_numeric; float32 used due to memory constraints; default axis for .apply() is axis = 0 AKA columns

# number of samples (= number of rows)
n_samples_cov = df_norm_col_data.shape[0]

## Compute the covariance matrix ##
# Transpose normalized dataset #
df_norm_col_data_T = df_norm_col_data.T 
print("Shape of transposed dataframe: ", df_norm_col_data_T.shape)

cov_matrix = (df_norm_col_data_T.dot(df_norm_col_data) / (n_samples_cov - 1)).astype(np.float32) # this performs matrix multiplication between the normalized dataframe and its transpose, then divides by the number of samples - 1.
print("Shape of covariance matrix: ", cov_matrix.shape)
print(cov_matrix.head())


Shape of transposed dataframe:  (128, 16000)
Shape of covariance matrix:  (128, 128)
        0         1         2         3         4         5         6    \
0  1.000000  0.786698  0.764707  0.734409  0.686022  0.630379  0.559150   
1  0.786698  1.000000  0.785210  0.774119  0.726373  0.683590  0.625686   
2  0.764707  0.785210  1.000000  0.793553  0.765094  0.735854  0.681103   
3  0.734409  0.774119  0.793553  1.000000  0.794645  0.774413  0.729699   
4  0.686022  0.726373  0.765094  0.794645  1.000000  0.787953  0.765323   

        7         8         9    ...       118       119       120       121  \
0  0.480732  0.405773  0.312933  ...  0.221022  0.312321  0.394548  0.479363   
1  0.553573  0.477462  0.400143  ...  0.134078  0.226238  0.308420  0.398630   
2  0.627418  0.553022  0.479421  ...  0.051382  0.140510  0.218828  0.314513   
3  0.683507  0.626333  0.560242  ... -0.020356  0.066470  0.145074  0.229270   
4  0.731356  0.688103  0.625377  ... -0.088881 -0.017414  0.0569

In [13]:
## Eigenvalue decomposition ##
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix) # eigenvalues: 1D array, eigenvectors: 2D array; .eigh used because covariance matrix is symmertric.

## Verify eigenvectors are unit vectors and orthogonal ##
# Unit Vector #
mag_vector = np.linalg.norm(eigenvectors[:, 1]) # this will find the magnitude of the second eigenvector
print("magnitude of second eigenvector: ", mag_vector)

## Orthogonality ##
orth_vectors = np.dot(eigenvectors[:, 0], eigenvectors[:, 1]) # checking orthogonality between first and second vector
print("Resulting dot product between first and second vectors: ", orth_vectors) # orth_vectors should be zero

magnitude of second eigenvector:  1.0
Resulting dot product between first and second vectors:  -6.9849193e-10


In [14]:
## Sort eigenvectors by largest to smallest eigenvalues ##
sorted_indices = np.argsort(eigenvalues)[::-1] # returns the indices that will sort the eigenvalues in descending order
sort_eigenvalues = eigenvalues[sorted_indices] # sorts eigenvalues based on the above indices
sort_eigenvectors = eigenvectors[:, sorted_indices] # sorts eigenvectors based on the above indices

## Select top four principle components ##
top_eigenvalues = sort_eigenvalues[:4]
top_eigenvectors = sort_eigenvectors[:, :4]
print("Length of top eigenvalues :", len(top_eigenvectors))
print("Top Eigenvalues: ", top_eigenvalues)
print("Top Eigenvectors: ", top_eigenvectors)


Length of top eigenvalues : 128
Top Eigenvalues:  [13.306583 13.1054   13.082196 13.001155]
Top Eigenvectors:  [[ 0.09680746 -0.05173286  0.1031086  -0.10938665]
 [ 0.10325825 -0.03995201  0.10935494 -0.10813938]
 [ 0.10532493 -0.03099287  0.1122936  -0.10300297]
 [ 0.1107772  -0.01998093  0.11185995 -0.09237975]
 [ 0.112863   -0.00823785  0.10683551 -0.0787755 ]
 [ 0.1146756   0.00314988  0.10028652 -0.06112517]
 [ 0.11529712  0.01326094  0.08929197 -0.04160826]
 [ 0.1141628   0.02264713  0.07669323 -0.01881727]
 [ 0.11483257  0.03356099  0.06117114  0.00334649]
 [ 0.11350455  0.0421562   0.04461475  0.02661297]
 [ 0.11291878  0.05027557  0.02636248  0.05069697]
 [ 0.11107863  0.06064375  0.00653144  0.07019877]
 [ 0.10756611  0.07135716 -0.01258069  0.08843081]
 [ 0.10411708  0.0787767  -0.03291107  0.10590815]
 [ 0.10197995  0.08595694 -0.05024014  0.11913924]
 [ 0.09895878  0.09389228 -0.06795614  0.12811688]
 [ 0.09743574  0.10066829 -0.08387578  0.13157015]
 [ 0.09587273  0.10767

In [15]:
## Transform the Data ##
transformed_data = np.dot(df_norm_col_data, top_eigenvectors)

# DataFrame
df_pca = pd.DataFrame(transformed_data, columns=[f'PC{i+1}' for i in range(4)]).astype(np.float32)
print("Shape of transformed data using top 4 eigenvectors: ", df_pca.shape)
print(df_pca.head())

Shape of transformed data using top 4 eigenvectors:  (16000, 4)
         PC1       PC2       PC3       PC4
0  -7.149179 -0.316087  0.925993 -0.708480
1   9.679392  1.032721 -2.119561  0.004836
2   7.328313  0.151282 -0.677274  0.274251
3 -10.142592 -0.413819  1.771847 -0.256651
4   1.286274  0.763547 -0.969172 -0.055263


In [16]:
## Euclidean Distance ##
start_time_PCA = time.time()

# Save the rows into an empty distance matrix
num_rows = df_pca.shape[0]
block_size = 10000
euclidean_distance_matrix_pca = np.zeros((num_rows, num_rows), dtype=np.float32)

# Euclidean Distance: Finding differences between samples in a pairwise fashion
for i in range(0, num_rows, block_size):
    for j in range(i, num_rows, block_size): # only computes for lower triangle (j >= i)
        block_i = df_pca.iloc[i:i+block_size].to_numpy()
        block_j = df_pca.iloc[j:j+block_size].to_numpy()
        
        # pairwise distances between blocks
        for row_i in range(block_i.shape[0]):
            for row_j in range(block_j.shape[0]):
                dist = euclidean_distance(block_i[row_i], block_j[row_j])
                euclidean_distance_matrix_pca[i+row_i, j+row_j] = dist 
                euclidean_distance_matrix_pca[j+row_j, i+row_i] = dist

end_time_PCA = time.time()

# Convert to DataFrame
euclidean_distance_matrix_pca = pd.DataFrame(euclidean_distance_matrix_pca)

# Calculate elapsed time
elapsed_time_WT = end_time_PCA - start_time_PCA

print(f'Time it takes to calculate euclidean distance on pca data: {elapsed_time_WT/60} minutes')

print("First few values: ", euclidean_distance_matrix_pca.head())
print("Last few values: ", euclidean_distance_matrix_pca.tail())

Time it takes to calculate euclidean distance on pca data: 24.60334169069926 minutes
First few values:         0          1          2          3          4          5      \
0   0.000000  17.169867  14.606588   3.144789   8.737324  13.144811   
1  17.169867   0.000000   2.908140  20.253763   8.476077   4.412591   
2  14.606588   2.908140   0.000000  17.658764   6.088915   1.575993   
3   3.144789  20.253763  17.658764   0.000000  11.813505  16.175327   
4   8.737324   8.476077   6.088915  11.813505   0.000000   4.761039   

       6          7          8          9      ...      15990      15991  \
0   0.943630  14.929703   1.111853  17.028442  ...   7.592680  11.049873   
1  16.462873   2.344785  16.148327   0.695409  ...   9.761385  13.299548   
2  13.909089   1.882027  13.608096   3.125930  ...   7.249131  11.173534   
3   3.827216  18.015120   4.138678  20.115471  ...  10.647809  12.875143   
4   8.009596   6.214656   7.693813   8.307345  ...   1.956178   8.504602   

       15992

**Comparing distance matrices**

In [17]:
## Randomly selecting pairs to calculate percentage of matching relationships ##
import random

euclidean_distance_matrix_np = np.array(euclidean_distance_matrix_2)
euclidean_distance_matrix_pca_np = np.array(euclidean_distance_matrix_pca)

# number of random pairs
n_samples = 5000

# randomly sample pairs of indices from the distance matrix
num_rows = euclidean_distance_matrix_np.shape[0]
random_pairs = [(random.randint(0, num_rows-1), random.randint(0, num_rows-1)) for _ in range(n_samples)]

# initial counters 
total_pairs = 0
pca_matching_relationships = 0

# Loop through the sampled pairs of cells 
for (i, j) in random_pairs:
    if i != j: # don't compare distances between same points
        # Ground truth distances
        dist_gt_1 = euclidean_distance_matrix_np[i, j]

        # Another random pair
        random_pair2 = (random.randint(0, num_rows - 1), random.randint(0, num_rows - 1))
        dist_gt_2 = euclidean_distance_matrix_np[random_pair2[0], random_pair2[1]]

        # Check relationship in ground truth matrix
        gt_relationship = dist_gt_1 > dist_gt_2

        # Distances from PCA distance matrix
        dist_pca_1 = euclidean_distance_matrix_pca_np[i, j]
        dist_pca_2 = euclidean_distance_matrix_pca_np[random_pair2[0], random_pair2[1]]

        # Check relationship in pca distance matrix
        pca_relationship = dist_pca_1 > dist_pca_2

        # Compare PCA relationship with ground truth relationship
        if pca_relationship == gt_relationship:
            pca_matching_relationships += 1

        total_pairs += 1

# Calculate the percentage of matching relationships
percentage_matching = (pca_matching_relationships / total_pairs) * 100

print(f"Percentage of matching relationships in PCA: {percentage_matching:.2f}%")

Percentage of matching relationships in PCA: 60.36%


In [19]:
## Randomly selecting pairs to calculate percentage of matching relationships ##
import random

euclidean_distance_matrix_np = np.array(euclidean_distance_matrix_2)
euclidean_distance_matrix_wt_np = np.array(euclidean_distance_matrix_wt)

# number of random pairs
n_samples = 1000

# randomly sample pairs of indices from the distance matrix
num_rows = euclidean_distance_matrix_np.shape[0]
random_pairs = [(random.randint(0, num_rows-1), random.randint(0, num_rows-1)) for _ in range(n_samples)]

# initial counters 
total_pairs = 0
wt_matching_relationships = 0

# Loop through the sampled pairs of cells 
for (i, j) in random_pairs:
    if i != j: # don't compare distances between same points
        # Ground truth distances
        dist_gt_1 = euclidean_distance_matrix_np[i, j]

        # Another random pair
        random_pair2 = (random.randint(0, num_rows - 1), random.randint(0, num_rows - 1))
        dist_gt_2 = euclidean_distance_matrix_np[random_pair2[0], random_pair2[1]]

        # Check relationship in ground truth matrix
        gt_relationship = dist_gt_1 > dist_gt_2

        # Distances from PCA distance matrix
        dist_wt_1 = euclidean_distance_matrix_wt_np[i, j]
        dist_wt_2 = euclidean_distance_matrix_wt_np[random_pair2[0], random_pair2[1]]

        # Check relationship in pca distance matrix
        wt_relationship = dist_wt_1 > dist_wt_2

        # Compare PCA relationship with ground truth relationship
        if wt_relationship == gt_relationship:
            wt_matching_relationships += 1

        total_pairs += 1

# Calculate the percentage of matching relationships
percentage_matching = (wt_matching_relationships / total_pairs) * 100

print(f"Percentage of matching relationships in wt: {percentage_matching:.2f}%")

Percentage of matching relationships in wt: 57.80%
